/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Manufacturing } from "./Manufacturing";
import { ManufacturingCountArgs } from "./ManufacturingCountArgs";
import { ManufacturingFindManyArgs } from "./ManufacturingFindManyArgs";
import { ManufacturingFindUniqueArgs } from "./ManufacturingFindUniqueArgs";
import { DeleteManufacturingArgs } from "./DeleteManufacturingArgs";
import { ManufacturingService } from "../manufacturing.service";
@graphql.Resolver(() => Manufacturing)
export class ManufacturingResolverBase {
  constructor(protected readonly service: ManufacturingService) {}

  async _manufacturingsMeta(
    @graphql.Args() args: ManufacturingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Manufacturing])
  async manufacturings(
    @graphql.Args() args: ManufacturingFindManyArgs
  ): Promise<Manufacturing[]> {
    return this.service.manufacturings(args);
  }

  @graphql.Query(() => Manufacturing, { nullable: true })
  async manufacturing(
    @graphql.Args() args: ManufacturingFindUniqueArgs
  ): Promise<Manufacturing | null> {
    const result = await this.service.manufacturing(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Manufacturing)
  async deleteManufacturing(
    @graphql.Args() args: DeleteManufacturingArgs
  ): Promise<Manufacturing | null> {
    try {
      return await this.service.deleteManufacturing(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
