/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProjectManagement } from "./ProjectManagement";
import { ProjectManagementCountArgs } from "./ProjectManagementCountArgs";
import { ProjectManagementFindManyArgs } from "./ProjectManagementFindManyArgs";
import { ProjectManagementFindUniqueArgs } from "./ProjectManagementFindUniqueArgs";
import { DeleteProjectManagementArgs } from "./DeleteProjectManagementArgs";
import { ProjectManagementService } from "../projectManagement.service";
@graphql.Resolver(() => ProjectManagement)
export class ProjectManagementResolverBase {
  constructor(protected readonly service: ProjectManagementService) {}

  async _projectManagementsMeta(
    @graphql.Args() args: ProjectManagementCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProjectManagement])
  async projectManagements(
    @graphql.Args() args: ProjectManagementFindManyArgs
  ): Promise<ProjectManagement[]> {
    return this.service.projectManagements(args);
  }

  @graphql.Query(() => ProjectManagement, { nullable: true })
  async projectManagement(
    @graphql.Args() args: ProjectManagementFindUniqueArgs
  ): Promise<ProjectManagement | null> {
    const result = await this.service.projectManagement(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProjectManagement)
  async deleteProjectManagement(
    @graphql.Args() args: DeleteProjectManagementArgs
  ): Promise<ProjectManagement | null> {
    try {
      return await this.service.deleteProjectManagement(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
