/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ComplianceManagement } from "./ComplianceManagement";
import { ComplianceManagementCountArgs } from "./ComplianceManagementCountArgs";
import { ComplianceManagementFindManyArgs } from "./ComplianceManagementFindManyArgs";
import { ComplianceManagementFindUniqueArgs } from "./ComplianceManagementFindUniqueArgs";
import { DeleteComplianceManagementArgs } from "./DeleteComplianceManagementArgs";
import { ComplianceManagementService } from "../complianceManagement.service";
@graphql.Resolver(() => ComplianceManagement)
export class ComplianceManagementResolverBase {
  constructor(protected readonly service: ComplianceManagementService) {}

  async _complianceManagementsMeta(
    @graphql.Args() args: ComplianceManagementCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ComplianceManagement])
  async complianceManagements(
    @graphql.Args() args: ComplianceManagementFindManyArgs
  ): Promise<ComplianceManagement[]> {
    return this.service.complianceManagements(args);
  }

  @graphql.Query(() => ComplianceManagement, { nullable: true })
  async complianceManagement(
    @graphql.Args() args: ComplianceManagementFindUniqueArgs
  ): Promise<ComplianceManagement | null> {
    const result = await this.service.complianceManagement(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ComplianceManagement)
  async deleteComplianceManagement(
    @graphql.Args() args: DeleteComplianceManagementArgs
  ): Promise<ComplianceManagement | null> {
    try {
      return await this.service.deleteComplianceManagement(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
