/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Ml } from "./Ml";
import { MlCountArgs } from "./MlCountArgs";
import { MlFindManyArgs } from "./MlFindManyArgs";
import { MlFindUniqueArgs } from "./MlFindUniqueArgs";
import { DeleteMlArgs } from "./DeleteMlArgs";
import { MlService } from "../ml.service";
@graphql.Resolver(() => Ml)
export class MlResolverBase {
  constructor(protected readonly service: MlService) {}

  async _mlsMeta(@graphql.Args() args: MlCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Ml])
  async mls(@graphql.Args() args: MlFindManyArgs): Promise<Ml[]> {
    return this.service.mls(args);
  }

  @graphql.Query(() => Ml, { nullable: true })
  async ml(@graphql.Args() args: MlFindUniqueArgs): Promise<Ml | null> {
    const result = await this.service.ml(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ml)
  async deleteMl(@graphql.Args() args: DeleteMlArgs): Promise<Ml | null> {
    try {
      return await this.service.deleteMl(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
