/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Hrms as PrismaHrms } from "@prisma/client";

export class HrmsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.HrmsCountArgs, "select">): Promise<number> {
    return this.prisma.hrms.count(args);
  }

  async hrmsItems(args: Prisma.HrmsFindManyArgs): Promise<PrismaHrms[]> {
    return this.prisma.hrms.findMany(args);
  }
  async hrms(args: Prisma.HrmsFindUniqueArgs): Promise<PrismaHrms | null> {
    return this.prisma.hrms.findUnique(args);
  }
  async createHrms(args: Prisma.HrmsCreateArgs): Promise<PrismaHrms> {
    return this.prisma.hrms.create(args);
  }
  async updateHrms(args: Prisma.HrmsUpdateArgs): Promise<PrismaHrms> {
    return this.prisma.hrms.update(args);
  }
  async deleteHrms(args: Prisma.HrmsDeleteArgs): Promise<PrismaHrms> {
    return this.prisma.hrms.delete(args);
  }
}
