/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Retail } from "./Retail";
import { RetailCountArgs } from "./RetailCountArgs";
import { RetailFindManyArgs } from "./RetailFindManyArgs";
import { RetailFindUniqueArgs } from "./RetailFindUniqueArgs";
import { DeleteRetailArgs } from "./DeleteRetailArgs";
import { RetailService } from "../retail.service";
@graphql.Resolver(() => Retail)
export class RetailResolverBase {
  constructor(protected readonly service: RetailService) {}

  async _retailsMeta(
    @graphql.Args() args: RetailCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Retail])
  async retails(@graphql.Args() args: RetailFindManyArgs): Promise<Retail[]> {
    return this.service.retails(args);
  }

  @graphql.Query(() => Retail, { nullable: true })
  async retail(
    @graphql.Args() args: RetailFindUniqueArgs
  ): Promise<Retail | null> {
    const result = await this.service.retail(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Retail)
  async deleteRetail(
    @graphql.Args() args: DeleteRetailArgs
  ): Promise<Retail | null> {
    try {
      return await this.service.deleteRetail(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
