/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Bi } from "./Bi";
import { BiCountArgs } from "./BiCountArgs";
import { BiFindManyArgs } from "./BiFindManyArgs";
import { BiFindUniqueArgs } from "./BiFindUniqueArgs";
import { DeleteBiArgs } from "./DeleteBiArgs";
import { BiService } from "../bi.service";
@graphql.Resolver(() => Bi)
export class BiResolverBase {
  constructor(protected readonly service: BiService) {}

  async _bisMeta(@graphql.Args() args: BiCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Bi])
  async bis(@graphql.Args() args: BiFindManyArgs): Promise<Bi[]> {
    return this.service.bis(args);
  }

  @graphql.Query(() => Bi, { nullable: true })
  async bi(@graphql.Args() args: BiFindUniqueArgs): Promise<Bi | null> {
    const result = await this.service.bi(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Bi)
  async deleteBi(@graphql.Args() args: DeleteBiArgs): Promise<Bi | null> {
    try {
      return await this.service.deleteBi(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
