/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Crm } from "./Crm";
import { CrmCountArgs } from "./CrmCountArgs";
import { CrmFindManyArgs } from "./CrmFindManyArgs";
import { CrmFindUniqueArgs } from "./CrmFindUniqueArgs";
import { DeleteCrmArgs } from "./DeleteCrmArgs";
import { CrmService } from "../crm.service";
@graphql.Resolver(() => Crm)
export class CrmResolverBase {
  constructor(protected readonly service: CrmService) {}

  async _crmsMeta(
    @graphql.Args() args: CrmCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Crm])
  async crms(@graphql.Args() args: CrmFindManyArgs): Promise<Crm[]> {
    return this.service.crms(args);
  }

  @graphql.Query(() => Crm, { nullable: true })
  async crm(@graphql.Args() args: CrmFindUniqueArgs): Promise<Crm | null> {
    const result = await this.service.crm(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Crm)
  async deleteCrm(@graphql.Args() args: DeleteCrmArgs): Promise<Crm | null> {
    try {
      return await this.service.deleteCrm(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
