/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { EcommerceIntegration } from "./EcommerceIntegration";
import { EcommerceIntegrationCountArgs } from "./EcommerceIntegrationCountArgs";
import { EcommerceIntegrationFindManyArgs } from "./EcommerceIntegrationFindManyArgs";
import { EcommerceIntegrationFindUniqueArgs } from "./EcommerceIntegrationFindUniqueArgs";
import { DeleteEcommerceIntegrationArgs } from "./DeleteEcommerceIntegrationArgs";
import { EcommerceIntegrationService } from "../ecommerceIntegration.service";
@graphql.Resolver(() => EcommerceIntegration)
export class EcommerceIntegrationResolverBase {
  constructor(protected readonly service: EcommerceIntegrationService) {}

  async _ecommerceIntegrationsMeta(
    @graphql.Args() args: EcommerceIntegrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [EcommerceIntegration])
  async ecommerceIntegrations(
    @graphql.Args() args: EcommerceIntegrationFindManyArgs
  ): Promise<EcommerceIntegration[]> {
    return this.service.ecommerceIntegrations(args);
  }

  @graphql.Query(() => EcommerceIntegration, { nullable: true })
  async ecommerceIntegration(
    @graphql.Args() args: EcommerceIntegrationFindUniqueArgs
  ): Promise<EcommerceIntegration | null> {
    const result = await this.service.ecommerceIntegration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EcommerceIntegration)
  async deleteEcommerceIntegration(
    @graphql.Args() args: DeleteEcommerceIntegrationArgs
  ): Promise<EcommerceIntegration | null> {
    try {
      return await this.service.deleteEcommerceIntegration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
